// Toate textele interfetei si ale emailurilor, intr-un singur loc, in romana.
export const t = {
  brand: "MentorMed",
  platformName: "Platforma de curs MentorMed",
  nav: { feed: "Resurse", profile: "Profil", admin: "Administrare", logout: "Ieși din cont" },
  login: {
    title: "Intră în cont",
    subtitle: "Folosește emailul cu care te-ai înscris în program.",
    email: "Email",
    password: "Parolă",
    submit: "Intră în cont",
    forgot: "Am uitat parola",
    invalid: "Email sau parolă incorecte.",
    throttled: "Prea multe încercări. Încearcă din nou peste 15 minute.",
    inactive: "Contul tău nu mai are acces activ. Scrie-ne la platforma@drbogdanchiper.ro.",
    sessionEnded: "Sesiunea de pe acest dispozitiv a fost închisă, pentru că contul este folosit pe alte două dispozitive.",
    noAccount: "Nu ai cont? Accesul se primește doar la invitație.",
  },
  forgot: {
    title: "Resetează parola",
    subtitle: "Îți trimitem un link de resetare pe email.",
    submit: "Trimite linkul",
    done: "Dacă adresa există în platformă, ai primit un email cu linkul de resetare.",
    back: "Înapoi la autentificare",
  },
  setPassword: {
    title: "Setează parola",
    subtitle: "Alege o parolă de cel puțin 10 caractere.",
    password: "Parolă nouă",
    confirm: "Repetă parola",
    submit: "Salvează parola",
    tooShort: "Parola trebuie să aibă cel puțin 10 caractere.",
    mismatch: "Parolele nu coincid.",
    compromised: "Această parolă apare în breșe de securitate cunoscute. Alege alta.",
    failed: "Nu am putut salva parola. Cere un link nou.",
  },
  terms: {
    title: "Termeni și confidențialitate",
    intro: "Înainte să continui, confirmă că ai citit și accepți documentele de mai jos.",
    accept: "Am citit și accept termenii și politica de confidențialitate",
    submit: "Continuă",
    required: "Trebuie să accepți pentru a continua.",
    termsLink: "Termeni și condiții",
    privacyLink: "Politica de confidențialitate",
  },
  mfa: {
    title: "Verificare în doi pași",
    subtitle: "Introdu codul din aplicația de autentificare.",
    code: "Cod din 6 cifre",
    submit: "Verifică",
    invalid: "Cod incorect. Încearcă din nou.",
  },
  feed: {
    title: "Resursele tale",
    empty: "Nu există resurse pentru tine încă. Revino după următoarea sesiune.",
    emptyFiltered: "Nicio resursă nu se potrivește filtrelor alese.",
    search: "Caută în resurse",
    all: "Toate",
    new: "Nou",
    types: { video: "Video", pdf: "PDF", text: "Text", link: "Link" },
  },
  resource: {
    attachments: "Materiale atașate",
    download: "Descarcă",
    open: "Deschide",
    back: "Înapoi la resurse",
    videoHelp: "Nu merge videoul? Reîncarcă pagina sau scrie-ne la platforma@drbogdanchiper.ro.",
  },
  profile: {
    title: "Profilul tău",
    firstName: "Prenume",
    lastName: "Nume",
    email: "Email",
    save: "Salvează",
    saved: "Datele au fost salvate.",
    changePassword: "Schimbă parola",
    required: "Completează prenumele și numele.",
  },
  common: { loading: "Se încarcă", error: "A apărut o eroare. Încearcă din nou.", cancel: "Anulează", save: "Salvează", delete: "Șterge", edit: "Editează", search: "Caută", none: "Niciuna" },
  email: {
    inviteSubject: "Invitație în platforma MentorMed",
    inviteTitle: "Bine ai venit în platforma MentorMed",
    inviteBody: "Ai primit acces la resursele programului. Apasă butonul de mai jos, setează-ți parola și intră în platformă.",
    inviteCta: "Setează parola",
    resetSubject: "Resetarea parolei pentru platforma MentorMed",
    resetTitle: "Resetează-ți parola",
    resetBody: "Am primit o cerere de resetare a parolei. Linkul este valabil o oră. Dacă nu ai cerut tu resetarea, ignoră acest email.",
    resetCta: "Alege o parolă nouă",
    footer: "Dr. Bogdan Chiper, MentorMed",
  },
} as const;
