// Toate textele interfetei si ale emailurilor, intr-un singur loc, in romana.
const ro = {
  brand: "MentorMed",
  platformName: "Platforma de curs MentorMed",
  nav: { feed: "Resurse", profile: "Profil", admin: "Administrare", logout: "Ieși din cont" },
  login: {
    title: "Intră în cont",
    subtitle: "Folosește emailul cu care te-ai înscris în program.",
    email: "Email",
    password: "Parolă",
    submit: "Intră în cont",
    forgot: "Am uitat parola",
    invalid: "Email sau parolă incorecte.",
    throttled: "Prea multe încercări. Încearcă din nou peste 15 minute.",
    inactive: "Contul tău nu mai are acces activ. Scrie-ne la contact@drbogdanchiper.ro.",
    sessionEnded: "Sesiunea de pe acest dispozitiv a fost închisă, pentru că contul este folosit pe alte două dispozitive.",
    noAccount: "Nu ai cont? Accesul se primește doar la invitație.",
  },
  forgot: {
    title: "Resetează parola",
    subtitle: "Îți trimitem un link de resetare pe email.",
    submit: "Trimite linkul",
    done: "Dacă adresa există în platformă, ai primit un email cu linkul de resetare.",
    back: "Înapoi la autentificare",
  },
  setPassword: {
    title: "Setează parola",
    subtitle: "Alege o parolă de cel puțin 10 caractere.",
    password: "Parolă nouă",
    confirm: "Repetă parola",
    submit: "Salvează parola",
    tooShort: "Parola trebuie să aibă cel puțin 10 caractere.",
    mismatch: "Parolele nu coincid.",
    compromised: "Această parolă apare în breșe de securitate cunoscute. Alege alta.",
    failed: "Nu am putut salva parola. Cere un link nou.",
  },
  terms: {
    title: "Termeni și confidențialitate",
    intro: "Înainte să continui, confirmă că ai citit și accepți documentele de mai jos.",
    accept: "Am citit și accept termenii și politica de confidențialitate",
    submit: "Continuă",
    required: "Trebuie să accepți pentru a continua.",
    termsLink: "Termeni și condiții",
    privacyLink: "Politica de confidențialitate",
  },
  mfa: {
    title: "Verificare în doi pași",
    subtitle: "Introdu codul din aplicația de autentificare.",
    code: "Cod din 6 cifre",
    submit: "Verifică",
    invalid: "Cod incorect. Încearcă din nou.",
  },
  feed: {
    title: "Resursele tale",
    empty: "Nu există resurse pentru tine încă. Revino după următoarea sesiune.",
    emptyFiltered: "Nicio resursă nu se potrivește filtrelor alese.",
    search: "Caută în resurse",
    all: "Toate",
    new: "Nou",
    types: { video: "Video", pdf: "PDF", text: "Text", link: "Link" },
  },
  resource: {
    attachments: "Materiale atașate",
    download: "Descarcă",
    open: "Deschide",
    back: "Înapoi la resurse",
    videoHelp: "Nu merge videoul? Reîncarcă pagina sau scrie-ne la contact@drbogdanchiper.ro.",
  },
  profile: {
    title: "Profilul tău",
    firstName: "Prenume",
    lastName: "Nume",
    email: "Email",
    save: "Salvează",
    saved: "Datele au fost salvate.",
    changePassword: "Schimbă parola",
    required: "Completează prenumele și numele.",
  },
  footer: {
    tagline: "Platforma privată pentru medicii înscriși în programul MentorMed.",
    platform: "Platformă",
    legal: "Legal",
    contact: "Contact",
    site: "drbogdanchiper.ro",
    program: "Programul MentorMed",
    rights: "Toate drepturile rezervate.",
  },
  home: {
    greeting: "Bună",
    newForYou: "Nou pentru tine",
    newCount: "resurse noi",
    continue: "Continuă de unde ai rămas",
    announcements: "Anunțuri",
    nextProgram: "Următorul MentorMed",
    nextProgramText: "Vezi detaliile și înscrie-te în următoarea ediție.",
    nextProgramCta: "Vezi programul",
    categories: "Categorii",
    yourGroups: "Grupurile tale",
    noNew: "Ești la zi cu toate resursele.",
    scroll: "Resursele tale",
  },
  common: { loading: "Se încarcă", error: "A apărut o eroare. Încearcă din nou.", cancel: "Anulează", save: "Salvează", delete: "Șterge", edit: "Editează", search: "Caută", none: "Niciuna" },
  email: {
    inviteSubject: "Invitație în platforma MentorMed",
    inviteTitle: "Bine ai venit în platforma MentorMed",
    inviteBody: "Ai primit acces la resursele programului. Apasă butonul de mai jos, setează-ți parola și intră în platformă.",
    inviteCta: "Setează parola",
    resetSubject: "Resetarea parolei pentru platforma MentorMed",
    resetTitle: "Resetează-ți parola",
    resetBody: "Am primit o cerere de resetare a parolei. Linkul este valabil o oră. Dacă nu ai cerut tu resetarea, ignoră acest email.",
    resetCta: "Alege o parolă nouă",
    footer: "Dr. Bogdan Chiper, MentorMed",
  },
} as const;

type Widen<T> = T extends string ? string : { [K in keyof T]: Widen<T[K]> };
export type Dict = Widen<typeof ro>;
export type Locale = "ro" | "en";

const en: Dict = {
  brand: "MentorMed",
  platformName: "MentorMed course platform",
  nav: { feed: "Resources", profile: "Profile", admin: "Administration", logout: "Sign out" },
  login: {
    title: "Sign in",
    subtitle: "Use the email you enrolled in the program with.",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    forgot: "I forgot my password",
    invalid: "Incorrect email or password.",
    throttled: "Too many attempts. Try again in 15 minutes.",
    inactive: "Your account no longer has active access. Write to us at contact@drbogdanchiper.ro.",
    sessionEnded: "The session on this device was closed because the account is used on two other devices.",
    noAccount: "No account? Access is by invitation only.",
  },
  forgot: {
    title: "Reset password",
    subtitle: "We will send you a reset link by email.",
    submit: "Send link",
    done: "If the address exists on the platform, you received an email with the reset link.",
    back: "Back to sign in",
  },
  setPassword: {
    title: "Set password",
    subtitle: "Choose a password of at least 10 characters.",
    password: "New password",
    confirm: "Repeat password",
    submit: "Save password",
    tooShort: "The password must have at least 10 characters.",
    mismatch: "The passwords do not match.",
    compromised: "This password appears in known data breaches. Choose another one.",
    failed: "We could not save the password. Request a new link.",
  },
  terms: {
    title: "Terms and privacy",
    intro: "Before you continue, confirm that you have read and accept the documents below.",
    accept: "I have read and accept the terms and the privacy policy",
    submit: "Continue",
    required: "You must accept to continue.",
    termsLink: "Terms and conditions",
    privacyLink: "Privacy policy",
  },
  mfa: {
    title: "Two step verification",
    subtitle: "Enter the code from your authenticator app.",
    code: "6 digit code",
    submit: "Verify",
    invalid: "Incorrect code. Try again.",
  },
  feed: {
    title: "Your resources",
    empty: "There are no resources for you yet. Come back after the next session.",
    emptyFiltered: "No resource matches the selected filters.",
    search: "Search resources",
    all: "All",
    new: "New",
    types: { video: "Video", pdf: "PDF", text: "Text", link: "Link" },
  },
  resource: {
    attachments: "Attached materials",
    download: "Download",
    open: "Open",
    back: "Back to resources",
    videoHelp: "Video not working? Reload the page or write to us at contact@drbogdanchiper.ro.",
  },
  profile: {
    title: "Your profile",
    firstName: "First name",
    lastName: "Last name",
    email: "Email",
    save: "Save",
    saved: "Your details were saved.",
    changePassword: "Change password",
    required: "Fill in your first and last name.",
  },
  footer: {
    tagline: "The private platform for doctors enrolled in the MentorMed program.",
    platform: "Platform",
    legal: "Legal",
    contact: "Contact",
    site: "drbogdanchiper.ro",
    program: "The MentorMed program",
    rights: "All rights reserved.",
  },
  home: {
    greeting: "Hello",
    newForYou: "New for you",
    newCount: "new resources",
    continue: "Continue where you left off",
    announcements: "Announcements",
    nextProgram: "Next MentorMed",
    nextProgramText: "See the details and enrol in the next edition.",
    nextProgramCta: "See the program",
    categories: "Categories",
    yourGroups: "Your groups",
    noNew: "You are up to date with all resources.",
    scroll: "Your resources",
  },
  common: { loading: "Loading", error: "Something went wrong. Try again.", cancel: "Cancel", save: "Save", delete: "Delete", edit: "Edit", search: "Search", none: "None" },
  email: {
    inviteSubject: "Invitation to the MentorMed platform",
    inviteTitle: "Welcome to the MentorMed platform",
    inviteBody: "You now have access to the program resources. Press the button below, set your password and enter the platform.",
    inviteCta: "Set password",
    resetSubject: "Password reset for the MentorMed platform",
    resetTitle: "Reset your password",
    resetBody: "We received a request to reset your password. The link is valid for one hour. If you did not request it, ignore this email.",
    resetCta: "Choose a new password",
    footer: "Dr. Bogdan Chiper, MentorMed",
  },
};

export const t: Dict = ro;
export const dictionaries: Record<Locale, Dict> = { ro, en };
